export const productCategories = [
  {
    category: "Lassi",
    thumbnailNavPosition: { bottom: -120 },
    thumbnailGap: 10,
    items: [
      {
        title: "Probiotic lassi",
        image: "/assets/ProductImages/Lassi 200g.png",
        subtext1: "Plain & silky",
        subtext2: "Classic probiotic drink",
        colorbg: "#88c0f8",
        imgStyle: { width: 340, height: 340, top: 0, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Lassi Strawberry 200g",
        image: "/assets/ProductImages/Lassi Strawberry 200g.png",
        subtext1: "Strawberry crush",
        subtext2: "Creamy & fruity",
        colorbg: "#e44556",
        imgStyle: { width: 340, height: 340, top: 0, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Lassi Blueberry 200g",
        image: "/assets/ProductImages/Lassi Blueberry 200g.png",
        subtext1: "Fresh blueberry punch",
        subtext2: "Sweet & tangy",
        colorbg: "#b691c5",
        imgStyle: { width: 340, height: 340, top: 0, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Lassi Mango 200g",
        image: "/assets/ProductImages/Lassi Mango 200g.png",
        subtext1: "Real mango puree",
        subtext2: "Tropical delight",
        colorbg: "#f28e47",
        imgStyle: { width: 340, height: 340, top: 0, marginBottom: 0 },
        selectedScale: 1.7,
      },
    ],
  },
  {
    category: "Buttermilk",
    thumbnailNavPosition: { bottom: -110 },
    thumbnailGap: 40,
    items: [
      {
        title: "Buttermilk Plain 400ml",
        image: "/assets/ProductImages/Buttermilk Plain 400ml.png",
        subtext1: "Classic creamy taste",
        subtext2: "Rich in probiotics",
        colorbg: "#f3cb8e",
        imgStyle: { width: 360, height: 260, top: 20, marginBottom: 0 },
        selectedScale: 1.5,
      },
      {
        title: "Buttermilk Sambaram 200ml",
        image: "/assets/ProductImages/Buttermilk Sambaram 200ml.png",
        subtext1: "Tamarind & spice twist",
        subtext2: "Cool and tangy",
        colorbg: "#93cda2",
        imgStyle: { width: 360, height: 260, top: 20, marginBottom: 0 },
        selectedScale: 1.5,
      },
      {
        title: "Buttermilk Jeera 200ml",
        image: "/assets/ProductImages/Buttermilk Jeera 200ml.png",
        subtext1: "Spiced with cumin",
        subtext2: "Gut-friendly refreshment",
        colorbg: "#5dc726",
        imgStyle: { width: 360, height: 260, top: 20, marginBottom: 0 },
        selectedScale: 1.5,
      },
    ],
  },

  {
    category: "Dahi",
    thumbnailNavPosition: { bottom: -80 },
    thumbnailGap: 30,
    items: [
      {
        title: "Dahi 100g",
        image: "/assets/ProductImages/Dahi 100g.png",
        subtext1: "Small pack",
        subtext2: "Fresh and creamy",
        colorbg: "#61b4e1",
        imgStyle: { width: 340, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.5,
      },

      {
        title: "Dahi 200g",
        image: "/assets/ProductImages/Dahi 200g.png",
        subtext1: "Family pack",
        subtext2: "Smooth texture",
        colorbg: "#61b4e1",
        imgStyle: { width: 340, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Dahi 350g",
        image: "/assets/ProductImages/Dahi 350g.png",
        subtext1: "Party size",
        subtext2: "Thick & creamy",
        colorbg: "#61b4e1",
        imgStyle: { width: 340, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Dahi 180g",
        image: "/assets/ProductImages/Dahi 180g.png",
        subtext1: "Mid-size snack",
        subtext2: "Rich in protein",
        colorbg: "#61b4e1",
        imgStyle: { width: 340, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.9,
      },
    ],
  },

  {
    category: "Paneer",
    thumbnailNavPosition: { bottom: -250 },
    thumbnailGap: 70,
    items: [
      {
        title: "Malai Paneer 100g",
        image: "/assets/ProductImages/Paneer 100g.png",
        subtext1: "Small cube pack",
        subtext2: "Fresh Indian cheese",
        colorbg: "#9ed1a6",
        imgStyle: { width: 150, height: 120,  marginBottom: 0 },
        selectedScale: 1.3,
      },
      {
        title: "Malai Paneer 200g",
        image: "/assets/ProductImages/Paneer 200g.png",
        subtext1: "Larger serving",
        subtext2: "Soft & creamy",
        colorbg: "#14871f",
        imgStyle: { width: 200, height: 150,  marginBottom: 0 },
        selectedScale: 1.5,
      },
    ],
  },
  {
    category: "Yogurt",
    thumbnailNavPosition: { bottom: -80 },
    thumbnailGap: 30,
    items: [
      {
        title: "Probiotic Strawberry Yogurt",
        image: "/assets/ProductImages/Yogurt Strawberry 100g.png",
        subtext1: "Strawberry yogurt cup",
        subtext2: "Fresh fruit bits",
        colorbg: "#fc758c",
        imgStyle: { width: 350, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Probiotic Mango Yogurt",
        image: "/assets/ProductImages/Yogurt Mango 100g.png",
        subtext1: "Mango yogurt cup",
        subtext2: "Sweet & tangy",
        colorbg: "#fdc858",
        imgStyle: { width: 350, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
    ],
  },

  {
    category: "Shrikhand",
    thumbnailNavPosition: { bottom: -80 },
    thumbnailGap: 30,
    items: [
      {
        title: "Elaichi Shrikhand",
        image: "/assets/ProductImages/Shrikhand - Elaichi 100g.png",
        subtext1: "Cardamom flavor",
        subtext2: "Delicate & creamy",
        colorbg: "#8bc960",
        imgStyle: { width: 350, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
      {
        title: "Badam & Pista Shrikhand",
        image: "/assets/ProductImages/Shrikhand - Badam & Pista 100g.png",
        subtext1: "Almond & pistachio",
        subtext2: "Aromatic saffron base",
        colorbg: "#e9b26d",
        imgStyle: { width: 350, height: 220, top: 40, marginBottom: 0 },
        selectedScale: 1.7,
      },
    ],
  },
];
// export const CarouselData = [

//   {
//     title: "Probiotic Rose Lassi",
//     image: "/assets/ProductImages/Lassi 200g.png",
//     subtext1: "Lorem ipsum dolor sit amem non",
//     subtext2: "Lorem ipsum dolor sit amem non",
//     colorbg: "#88c0f8",
//   },
//   {
//     title: "Probiotic Blueberry Lassi ",
//     image: "/assets/ProductImages/Lassi Blueberry 200g.png",
//     subtext1: "Lorem ipsum dolor sit amem non",
//     subtext2: "Lorem ipsum dolor sit amem non",
//     colorbg: "#b691c5",
//   },
//   {
//     title: "Probiotic Mango Lassi ",
//     image: "/assets/ProductImages/Lassi Mango 200g.png",
//     subtext1: "Lorem ipsum dolor sit amem non",
//     subtext2: "Lorem ipsum dolor sit amem non",
//     colorbg: "#f28e47",
//   },
//   {
//     title: "Probiotic strawbery Lassi ",
//     image: "/assets/ProductImages/Lassi Strawberry 200g.png",
//     subtext1: "Lorem ipsum dolor sit amem non",
//     subtext2: "Lorem ipsum dolor sit amem non",
//     colorbg: "#e44556",
//   },
// ];
